panel.ventanaInicial.encabezado  =  Rutila home window
panel.ventanaInicial.titulo  =  Rutila Bar
panel.ventanaInicial.infoIdioma  =  Select a language before you begin
panel.ventanaInicial.infoApp  =  APP FOR SINGLES

panel.ventanaregistroPersona.encabezado  =  Register User Window
panel.ventanaregistroPersona.titulo  =  ARE YOU READY TO BE PART \nOF SINGLES NIGHT?
panel.ventanaregistroPersona.infoPersona  =  Enter the information requested below
panel.ventanaregistroPersona.nombre  =  First name
panel.ventanaregistroPersona.apellido  =  Second name
panel.ventanaregistroPersona.fechaNacimiento  =  Date of birth
panel.ventanaregistroPersona.programaAcademico  =  Academic program
panel.ventanaregistroPersona.universidad  =  university
panel.ventanaregistroPersona.numeroDocumento  =  ID number
panel.ventanaregistroPersona.genero  =  gender
panel.ventanaregistroPersona.masculino  = male
panel.ventanaregistroPersona.femenino  =  female
panel.ventanaregistroPersona.fotoPerfil  =  Profile picture
panel.ventanaregistroPersona.subirFoto  =  Upload Photo
panel.ventanaregistroPersona.guardar  =  Save
panel.ventanaregistroPersona.listaIdiomas.cambio  =  change language
panel.ventanaregistroPersona.listaIdiomas.español  =  spanish
panel.ventanaregistroPersona.listaIdiomas.ingles  =  english
panel.ventanaregistroPersona.listaIdiomas.frances  =  french
panel.ventanaregistroPersona.listaIdiomas.ruso  =  russian
panel.ventanaregistroPersona.listaIdiomas.latin  =  latin
panel.ventanaregistroPersona.listaIdiomas.japones  =  japanese
panel.ventanaregistroPersona.boton.volver  =  back


panel.ventanaPrincipal.encabezado  =  Home screen
panel.ventanaPrincipal.titulo  =  RUTILA
panel.ventanaPrincipal.boton.perfil  =  MY PROFILE
panel.ventanaPrincipal.boton.solteros  =  VIEW SINGLES
panel.ventanaPrincipal.boton.parejas  =  VIEW COUPLES
panel.ventanaPrincipal.listaIdiomas.cambio  =  change language
panel.ventanaPrincipal.listaIdiomas.español  =  spanish
panel.ventanaPrincipal.listaIdiomas.ingles  =  english
panel.ventanaPrincipal.listaIdiomas.frances  =  french
panel.ventanaPrincipal.listaIdiomas.ruso  =  russian
panel.ventanaPrincipal.listaIdiomas.latin  =  latin
panel.ventanaPrincipal.listaIdiomas.japones  =  japanese
panel.ventanaPrincipal.boton.volver  =  back

panel.miPerfil.nombre  = First name
panel.miPerfil.apellido  =  Second name
panel.miPerfil.edad  =  age
panel.miPerfil.genero  =  gender
panel.miPerfil.universidad  =  university
panel.miPerfil.carrera  =  Major

panel.pareja.titulo  =  Couples registered tonight
panel.pareja.tituloLista  =  couples
panel.pareja.boton.separarPareja  =  SEPARATE COUPLE
panel.pareja.persona1.nombre  =  First name
panel.pareja.persona1.apellido  =  Last name
panel.pareja.persona1.edad  =  age
panel.pareja.persona1.genero  =  gender
panel.pareja.persona1.universidad  =  university
panel.pareja.persona1.carrera  =  major
panel.pareja.persona2.nombre  =  first name
panel.pareja.persona2.apellido  =  Last name
panel.pareja.persona2.edad  =  age
panel.pareja.persona2.genero  =  gender
panel.pareja.persona2.universidad  =  university
panel.pareja.persona2.carrera  =  major

panel.soltero.titulo = Singles registered tonight
panel.soltero.columna.nombre  =  First name
panel.soltero.columna.apellido  =  Last name
panel.soltero.columna.genero  =  gender
panel.soltero.columna.edad  =  age
panel.soltero.columna.universidad  =  university
panel.soltero.boton.verDetalles  =  View Details
panel.soltero.boton.emparejar  =  MATCH
panel.soltero.nombre  =  first name
panel.soltero.apellido  =  last name 
panel.soltero.edad  =  age
panel.soltero.genero  =  gender
panel.soltero.universidad  =  university
panel.soltero.carrera  =  major