panel.ventanaInicial.encabezado  =  Fenêtre d'accueil Rutila
panel.ventanaInicial.titulo   =   BAR RUTILA
panel.ventanaInicial.infoIdioma  =  Sélectionnez une langue avant de commencer
panel.ventanaInicial.infoApp  =  APPLICATION POUR CÉLIBATAIRES

panel.ventanaregistroPersona.encabezado  =  Fenêtre d'inscription utilisateur
panel.ventanaregistroPersona.titulo  =  ÊTES-VOUS PRÊT À FAIRE PARTIE \nDE LA SOIRÉE DES CÉLIBATAIRES ?
panel.ventanaregistroPersona.infoPersona  =  Entrez les informations demandées ci-dessous
panel.ventanaregistroPersona.nombre  =  Prénom
panel.ventanaregistroPersona.apellido  =  Nom de famille
panel.ventanaregistroPersona.fechaNacimiento  =  Date de naissance \n(DD/MM/AAAA):
panel.ventanaregistroPersona.programaAcademico  =  Programme académique
panel.ventanaregistroPersona.universidad  =  université
panel.ventanaregistroPersona.numeroDocumento  =  Numéro d'identité
panel.ventanaregistroPersona.genero  =  genre
panel.ventanaregistroPersona.masculino  = masculin
panel.ventanaregistroPersona.femenino  =  féminin
panel.ventanaregistroPersona.fotoPerfil  =  Photo de profil
panel.ventanaregistroPersona.subirFoto  =  Télécharger une photo
panel.ventanaregistroPersona.guardar  =  Enregistrer
panel.ventanaregistroPersona.listaIdiomas.cambio  =  changer de langue
panel.ventanaregistroPersona.listaIdiomas.español  =  espagnol
panel.ventanaregistroPersona.listaIdiomas.ingles  =  anglais
panel.ventanaregistroPersona.listaIdiomas.frances  =  français
panel.ventanaregistroPersona.listaIdiomas.ruso  =  russe
panel.ventanaregistroPersona.listaIdiomas.latin  =  latin
panel.ventanaregistroPersona.listaIdiomas.japones  =  japonais
panel.ventanaregistroPersona.boton.volver  =  retour
panel.ventanaregistroPersona.label.cuentacreada = Vous avez déjà un compte?
panel.ventanaregistroPersona.boton.iniciarsesion = Connectez-vous ici

panel.ventanainiciarsesion.label.informacion = CONNECTEZ-VOUS POUR ACCÉDER \nÀ L'APP RUTILA BAR
panel.ventanainiciarsesion.label.numerodocumento = Numéro de document:
panel.ventanainiciarsesion.boton.volver = RETOUR
panel.ventanainiciarsesion.boton.entrar = ENTRER

panel.ventanaPrincipal.encabezado  =  Écran d'accueil
panel.ventanaPrincipal.titulo  =  RUTILA
panel.ventanaPrincipal.boton.perfil  =  MON PROFIL
panel.ventanaPrincipal.boton.solteros  =  VOIR LES CÉLIBATAIRES
panel.ventanaPrincipal.boton.parejas  =  VOIR LES COUPLES
panel.ventanaPrincipal.listaIdiomas.cambio  =  changer de langue
panel.ventanaPrincipal.listaIdiomas.español  =  espagnol
panel.ventanaPrincipal.listaIdiomas.ingles  =  anglais
panel.ventanaPrincipal.listaIdiomas.frances  =  français
panel.ventanaPrincipal.listaIdiomas.ruso  =  russe
panel.ventanaPrincipal.listaIdiomas.latin  =  latin
panel.ventanaPrincipal.listaIdiomas.japones  =  japonais
panel.ventanaPrincipal.boton.volver  =  retour

panel.miPerfil.nombre  = Prénom
panel.miPerfil.apellido  =  Nom de famille
panel.miPerfil.edad  =  âge
panel.miPerfil.genero  =  genre
panel.miPerfil.universidad  =  université
panel.miPerfil.carrera  =  spécialité

panel.pareja.titulo  =  Couples inscrits ce soir
panel.pareja.tituloLista  =  couples
panel.pareja.boton.separarPareja  =  SÉPARER LE COUPLE
panel.pareja.persona1.nombre  =  Prénom
panel.pareja.persona1.apellido  =  Nom de famille
panel.pareja.persona1.edad  =  âge
panel.pareja.persona1.genero  =  genre
panel.pareja.persona1.universidad  =  université
panel.pareja.persona1.carrera  =  spécialité
panel.pareja.persona2.nombre  =  Prénom
panel.pareja.persona2.apellido  =  Nom de famille
panel.pareja.persona2.edad  =  âge
panel.pareja.persona2.genero  =  genre
panel.pareja.persona2.universidad  =  université
panel.pareja.persona2.carrera  =  spécialité

panel.soltero.titulo = Célibataires inscrits ce soir
panel.soltero.columna.nombre  =  Prénom
panel.soltero.columna.apellido  =  Nom de famille
panel.soltero.columna.genero  =  genre
panel.soltero.columna.edad  =  âge
panel.soltero.columna.universidad  =  université
panel.soltero.boton.verDetalles  =  Voir les détails
panel.soltero.boton.emparejar  =  ASSOCIER
panel.soltero.nombre  =  Prénom
panel.soltero.apellido  =  Nom de famille 
panel.soltero.edad  =  âge
panel.soltero.genero  =  genre
panel.soltero.universidad  =  université
panel.soltero.carrera  =  spécialité

appsoltero.joptionpane.messagedialog.imagencargada.exitosa   =   Image chargée avec succès
appsoltero.joptionpane.messagedialog.controledad   =   Vous êtes encore mineur. Vous ne pouvez pas entrer dans le bar
appsoltero.joptionpane.messagedialog.registroexitoso   =   Célibataire enregistré avec succès
appsoltero.joptionpane.excepciones.fechanacimiento   =   La date de naissance est incorrecte
appsoltero.joptionpane.excepciones.genero   =   Vous n'avez pas sélectionné votre genre
appsoltero.joptionpane.excepciones.documento   =   Numéro de document invalide
appsoltero.joptionpane.excepciones.apellido   =   Nom de famille invalide
appsoltero.joptionpane.excepciones.nombre   =   Prénom invalide
appsoltero.joptionpane.excepciones.universidad   =   Nom d'université invalide
appsoltero.joptionpane.excepciones.carrera   =   Filière universitaire invalide
appsoltero.joptionpane.excepciones.imagen   =   Vous n'avez pas sélectionné de photo de profil
appsoltero.joptionpane.excepciones.number   =   Numéro de document invalide
appsoltero.joptionpane.documentonoregistrado   =   Ce numéro de document n'est pas enregistré

appsoltero.joptionpane.messagedialog.iniciosesioncorrecto.uno   =   Bienvenue, 
appsoltero.joptionpane.messagedialog.iniciosesioncorrecto.dos   =    à rutila
appsoltero.joptionpane.messagedialog.emparejar.nocorrecto   =   Sélectionnez un célibataire pour effectuer cette action
appsoltero.joptionpane.messagedialog.emparejar.noseencuentrasoltero   =   Célibataire non trouvé
appsoltero.joptionpane.messagedialog.emparejar.seleccionincorrecta   =   Vous ne pouvez pas vous mettre en couple avec vous-même
appsoltero.joptionpane.messagedialog.emparejar.seleccioncorrecta   =   Couple formé avec succès !