panel.ventanaInicial.encabezado  =  Rutila\u306E\u30DB\u30FC\u30E0\u753B\u9762
panel.ventanaInicial.titulo  =  Rutila\u30D0\u30FC
panel.ventanaInicial.infoIdioma  =  \u958B\u59CB\u3059\u308B\u524D\u306B\u8A00\u8A9E\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044
panel.ventanaInicial.infoApp  =  \u30B7\u30F3\u30B0\u30EB\u5411\u3051\u30A2\u30D7\u30EA

panel.ventanaregistroPersona.encabezado  =  \u30E6\u30FC\u30B6\u30FC\u767B\u9332\u753B\u9762
panel.ventanaregistroPersona.titulo  =  \u30B7\u30F3\u30B0\u30EB\u30CA\u30A4\u30C8\u306E\u4E00\u54E1\u306B\u306A\u308B\u6E96\u5099\u306F\u3067\u304D\u3066\u3044\u307E\u3059\u304B\uFF1F\n
panel.ventanaregistroPersona.infoPersona  =  \u4EE5\u4E0B\u306E\u60C5\u5831\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044
panel.ventanaregistroPersona.nombre  =  \u540D
panel.ventanaregistroPersona.apellido  =  \u59D3
panel.ventanaregistroPersona.fechaNacimiento  =  \u751F\u5E74\u6708\u65E5
panel.ventanaregistroPersona.programaAcademico  =  \u5B66\u7FD2\u30D7\u30ED\u30B0\u30E9\u30E0
panel.ventanaregistroPersona.universidad  =  \u5927\u5B66
panel.ventanaregistroPersona.numeroDocumento  =  \u8EAB\u5206\u8A3C\u756A\u53F7
panel.ventanaregistroPersona.genero  =  \u6027\u5225
panel.ventanaregistroPersona.masculino  = \u7537\u6027
panel.ventanaregistroPersona.femenino  =  \u5973\u6027
panel.ventanaregistroPersona.fotoPerfil  =  \u30D7\u30ED\u30D5\u30A3\u30FC\u30EB\u5199\u771F
panel.ventanaregistroPersona.subirFoto  =  \u5199\u771F\u3092\u30A2\u30C3\u30D7\u30ED\u30FC\u30C9
panel.ventanaregistroPersona.guardar  =  \u4FDD\u5B58
panel.ventanaregistroPersona.listaIdiomas.cambio  =  \u8A00\u8A9E\u3092\u5909\u66F4
panel.ventanaregistroPersona.listaIdiomas.español  =  \u30B9\u30DA\u30A4\u30F3\u8A9E
panel.ventanaregistroPersona.listaIdiomas.ingles  =  \u82F1\u8A9E
panel.ventanaregistroPersona.listaIdiomas.frances  =  \u30D5\u30E9\u30F3\u30B9\u8A9E
panel.ventanaregistroPersona.listaIdiomas.ruso  =  \u30ED\u30B7\u30A2\u8A9E
panel.ventanaregistroPersona.listaIdiomas.latin  =  \u30E9\u30C6\u30F3\u8A9E
panel.ventanaregistroPersona.listaIdiomas.japones  =  \u65E5\u672C\u8A9E
panel.ventanaregistroPersona.boton.volver  =  \u623B\u308B

panel.ventanaPrincipal.encabezado  =  \u30DB\u30FC\u30E0\u753B\u9762
panel.ventanaPrincipal.titulo  =  RUTILA
panel.ventanaPrincipal.boton.perfil  =  \u30DE\u30A4\u30D7\u30ED\u30D5\u30A3\u30FC\u30EB
panel.ventanaPrincipal.boton.solteros  =  \u30B7\u30F3\u30B0\u30EB\u3092\u898B\u308B
panel.ventanaPrincipal.boton.parejas  =  \u30AB\u30C3\u30D7\u30EB\u3092\u898B\u308B
panel.ventanaPrincipal.listaIdiomas.cambio  =  \u8A00\u8A9E\u3092\u5909\u66F4
panel.ventanaPrincipal.listaIdiomas.español  =  \u30B9\u30DA\u30A4\u30F3\u8A9E
panel.ventanaPrincipal.listaIdiomas.ingles  =  \u82F1\u8A9E
panel.ventanaPrincipal.listaIdiomas.frances  =  \u30D5\u30E9\u30F3\u30B9\u8A9E
panel.ventanaPrincipal.listaIdiomas.ruso  =  \u30ED\u30B7\u30A2\u8A9E
panel.ventanaPrincipal.listaIdiomas.latin  =  \u30E9\u30C6\u30F3\u8A9E
panel.ventanaPrincipal.listaIdiomas.japones  =  \u65E5\u672C\u8A9E
panel.ventanaPrincipal.boton.volver  =  \u623B\u308B

panel.miPerfil.nombre  = \u540D
panel.miPerfil.apellido  =  \u59D3
panel.miPerfil.edad  =  \u5E74\u9F62
panel.miPerfil.genero  =  \u6027\u5225
panel.miPerfil.universidad  =  \u5927\u5B66
panel.miPerfil.carrera  =  \u5C02\u653B

panel.pareja.titulo  =  \u4ECA\u591C\u767B\u9332\u3055\u308C\u305F\u30AB\u30C3\u30D7\u30EB
panel.pareja.tituloLista  =  \u30AB\u30C3\u30D7\u30EB
panel.pareja.boton.separarPareja  =  \u30AB\u30C3\u30D7\u30EB\u3092\u5206\u3051\u308B
panel.pareja.persona1.nombre  =  \u540D
panel.pareja.persona1.apellido  =  \u59D3
panel.pareja.persona1.edad  =  \u5E74\u9F62
panel.pareja.persona1.genero  =  \u6027\u5225
panel.pareja.persona1.universidad  =  \u5927\u5B66
panel.pareja.persona1.carrera  =  \u5C02\u653B
panel.pareja.persona2.nombre  =  \u540D
panel.pareja.persona2.apellido  =  \u59D3
panel.pareja.persona2.edad  =  \u5E74\u9F62
panel.pareja.persona2.genero  =  \u6027\u5225
panel.pareja.persona2.universidad  =  \u5927\u5B66
panel.pareja.persona2.carrera  =  \u5C02\u653B

panel.soltero.titulo = \u4ECA\u591C\u767B\u9332\u3055\u308C\u305F\u30B7\u30F3\u30B0\u30EB
panel.soltero.columna.nombre  =  \u540D
panel.soltero.columna.apellido  =  \u59D3
panel.soltero.columna.genero  =  \u6027\u5225
panel.soltero.columna.edad  =  \u5E74\u9F62
panel.soltero.columna.universidad  =  \u5927\u5B66
panel.soltero.boton.verDetalles  =  \u8A73\u7D30\u3092\u898B\u308B
panel.soltero.boton.emparejar  =  \u30DE\u30C3\u30C1\u3059\u308B
panel.soltero.nombre  =  \u540D
panel.soltero.apellido  =  \u59D3 
panel.soltero.edad  =  \u5E74\u9F62
panel.soltero.genero  =  \u6027\u5225
panel.soltero.universidad  =  \u5927\u5B66
panel.soltero.carrera  =  \u5C02\u653B