panel.ventanaInicial.encabezado  =  Fenestra initialis Rutila
panel.ventanaInicial.titulo  =  Bar Rutila
panel.ventanaInicial.infoIdioma  =  Linguam elige antequam incipias
panel.ventanaInicial.infoApp  =  APPLICATIO PRO SOLUTIS

panel.ventanaregistroPersona.encabezado  =  Fenestra inscriptionis usoris
panel.ventanaregistroPersona.titulo  =  PARATUSNE ES AD ESSE PARS \nNOCTIS SOLUTORUM?
panel.ventanaregistroPersona.infoPersona  =  Inseras informationem infra petitam
panel.ventanaregistroPersona.nombre  =  Praenomen
panel.ventanaregistroPersona.apellido  =  Cognomen
panel.ventanaregistroPersona.fechaNacimiento  =  Dies natalis
panel.ventanaregistroPersona.programaAcademico  =  Programma academicum
panel.ventanaregistroPersona.universidad  =  universitas
panel.ventanaregistroPersona.numeroDocumento  =  Numerus documenti
panel.ventanaregistroPersona.genero  =  genus
panel.ventanaregistroPersona.masculino  = masculinum
panel.ventanaregistroPersona.femenino  =  femininum
panel.ventanaregistroPersona.fotoPerfil  =  Imago profili
panel.ventanaregistroPersona.subirFoto  =  Imaginem caricare
panel.ventanaregistroPersona.guardar  =  Servare
panel.ventanaregistroPersona.listaIdiomas.cambio  =  linguam mutare
panel.ventanaregistroPersona.listaIdiomas.español  =  hispanica
panel.ventanaregistroPersona.listaIdiomas.ingles  =  anglica
panel.ventanaregistroPersona.listaIdiomas.frances  =  gallica
panel.ventanaregistroPersona.listaIdiomas.ruso  =  russica
panel.ventanaregistroPersona.listaIdiomas.latin  =  latina
panel.ventanaregistroPersona.listaIdiomas.japones  =  iaponica
panel.ventanaregistroPersona.boton.volver  =  redire
panel.ventanaregistroPersona.label.cuentacreada = Rationem iam creasti?
panel.ventanaregistroPersona.boton.iniciarsesion = Hic intra

panel.ventanainiciarsesion.label.informacion = INTRA UT ACCEDAS \nAD APPLICATIONEM RUTILA BAR
panel.ventanainiciarsesion.label.numerodocumento = Numerus documenti:
panel.ventanainiciarsesion.boton.volver = REVERTERE
panel.ventanainiciarsesion.boton.entrar = INTRARE

panel.ventanaPrincipal.encabezado  =  Schermata principalis
panel.ventanaPrincipal.titulo  =  RUTILA
panel.ventanaPrincipal.boton.perfil  =  PROFILUM MEUM
panel.ventanaPrincipal.boton.solteros  =  SOLUTOS VIDERE
panel.ventanaPrincipal.boton.parejas  =  CONIUGES VIDERE
panel.ventanaPrincipal.listaIdiomas.cambio  =  linguam mutare
panel.ventanaPrincipal.listaIdiomas.español  =  hispanica
panel.ventanaPrincipal.listaIdiomas.ingles  =  anglica
panel.ventanaPrincipal.listaIdiomas.frances  =  gallica
panel.ventanaPrincipal.listaIdiomas.ruso  =  russica
panel.ventanaPrincipal.listaIdiomas.latin  =  latina
panel.ventanaPrincipal.listaIdiomas.japones  =  iaponica
panel.ventanaPrincipal.boton.volver  =  redire

panel.miPerfil.nombre  = Praenomen
panel.miPerfil.apellido  =  Cognomen
panel.miPerfil.edad  =  aetas
panel.miPerfil.genero  =  genus
panel.miPerfil.universidad  =  universitas
panel.miPerfil.carrera  =  studium

panel.pareja.titulo  =  Coniuges hac nocte inscripti
panel.pareja.tituloLista  =  coniuges
panel.pareja.boton.separarPareja  =  CONIUGES SEPARARE
panel.pareja.persona1.nombre  =  Praenomen
panel.pareja.persona1.apellido  =  Cognomen
panel.pareja.persona1.edad  =  aetas
panel.pareja.persona1.genero  =  genus
panel.pareja.persona1.universidad  =  universitas
panel.pareja.persona1.carrera  =  studium
panel.pareja.persona2.nombre  =  Praenomen
panel.pareja.persona2.apellido  =  Cognomen
panel.pareja.persona2.edad  =  aetas
panel.pareja.persona2.genero  =  genus
panel.pareja.persona2.universidad  =  universitas
panel.pareja.persona2.carrera  =  studium

panel.soltero.titulo = Soluti hac nocte inscripti
panel.soltero.columna.nombre  =  Praenomen
panel.soltero.columna.apellido  =  Cognomen
panel.soltero.columna.genero  =  genus
panel.soltero.columna.edad  =  aetas
panel.soltero.columna.universidad  =  universitas
panel.soltero.boton.verDetalles  =  Detalia videre
panel.soltero.boton.emparejar  =  SOCIARE
panel.soltero.nombre  =  Praenomen
panel.soltero.apellido  =  Cognomen 
panel.soltero.edad  =  aetas
panel.soltero.genero  =  genus
panel.soltero.universidad  =  universitas
panel.soltero.carrera  =  studium