panel.ventanaInicial.encabezado  =  Ventana de inicio
panel.ventanaInicial.titulo   =  BAR RUTILA
panel.ventanaInicial.infoIdioma  =  Selecciona un idioma antes de comenzar 
panel.ventanaInicial.infoApp  =  APP PARA SOLTEROS

panel.ventanaregistroPersona.encabezado  =  Ventana de registro
panel.ventanaregistroPersona.titulo  =  ¿ESTAS LISTO PARA SER PARTE \nDE LA NOCHE DE SOLTEROS?
panel.ventanaregistroPersona.infoPersona  =  Ingrese la informacion que se solicita a continuacion 
panel.ventanaregistroPersona.nombre  =  Nombre
panel.ventanaregistroPersona.apellido  =  Apellido
panel.ventanaregistroPersona.fechaNacimiento  =  Fecha de nacimiento \n(DD/MM/AAAA):
panel.ventanaregistroPersona.programaAcademico  =  Programa academico
panel.ventanaregistroPersona.universidad  =  universidad
panel.ventanaregistroPersona.numeroDocumento  =  Numero de identificacion
panel.ventanaregistroPersona.genero  =  Genero
panel.ventanaregistroPersona.masculino  = Masculino
panel.ventanaregistroPersona.femenino  =  Femenino
panel.ventanaregistroPersona.fotoPerfil  =  Foto de perfil 
panel.ventanaregistroPersona.subirFoto  =  SUBIR FOTO
panel.ventanaregistroPersona.guardar  =  GUARDAR
panel.ventanaregistroPersona.listaIdiomas.cambio  =  Cambiar idioma
panel.ventanaregistroPersona.listaIdiomas.español  =  español
panel.ventanaregistroPersona.listaIdiomas.ingles  =  ingles
panel.ventanaregistroPersona.listaIdiomas.frances  =  frances
panel.ventanaregistroPersona.listaIdiomas.ruso  =  ruso
panel.ventanaregistroPersona.listaIdiomas.latin  =  latin
panel.ventanaregistroPersona.listaIdiomas.japones  =  japones
panel.ventanaregistroPersona.boton.volver  =  VOLVER
panel.ventanaregistroPersona.label.cuentacreada   =   ¿Ya creaste tu cuenta?
panel.ventanaregistroPersona.boton.iniciarsesion   = Inicia sesión aquí

panel.ventanaPrincipal.encabezado  =  Ventana Principal
panel.ventanaPrincipal.titulo  =  RUTILA
panel.ventanaPrincipal.boton.perfil  =  MI PERFIL
panel.ventanaPrincipal.boton.solteros  =  VER SOLTEROS
panel.ventanaPrincipal.boton.parejas  =  VER PAREJAS
panel.ventanaPrincipal.listaIdiomas.cambio  =  Cambiar idioma
panel.ventanaPrincipal.listaIdiomas.español  =  español
panel.ventanaPrincipal.listaIdiomas.ingles  =  ingles
panel.ventanaPrincipal.listaIdiomas.frances  =  frances
panel.ventanaPrincipal.listaIdiomas.ruso  =  ruso
panel.ventanaPrincipal.listaIdiomas.latin  =  latin
panel.ventanaPrincipal.listaIdiomas.japones  =  japones
panel.ventanaPrincipal.boton.volver  =  VOLVER

panel.ventanainiciarsesion.label.informacion   =   INICIA SESIÓN PARA ENTRAR \nA LA APP DE RUTILA BAR
panel.ventanainiciarsesion.label.numerodocumento   =   Número de documento:
panel.ventanainiciarsesion.boton.volver   =   VOLVER
panel.ventanainiciarsesion.boton.entrar   =   ENTRAR

panel.miPerfil.nombre  = nombre
panel.miPerfil.apellido  =  apellido
panel.miPerfil.edad  =  edad
panel.miPerfil.genero  =  genero
panel.miPerfil.universidad  =  universidad
panel.miPerfil.carrera  =  carrera

panel.pareja.titulo  =  Parejas registradas esta noche 
panel.pareja.tituloLista  =  Parejas
panel.pareja.boton.separarPareja  =  Separar parejas
panel.pareja.persona1.nombre  =  Nombre
panel.pareja.persona1.apellido  =  Apellido
panel.pareja.persona1.edad  =  edad
panel.pareja.persona1.genero  =  Genero
panel.pareja.persona1.universidad  =  universidad
panel.pareja.persona1.carrera  =  carrera
panel.pareja.persona2.nombre  =  Nombre
panel.pareja.persona2.apellido  =  Apellido
panel.pareja.persona2.edad  =  Edad
panel.pareja.persona2.genero  =  Genero
panel.pareja.persona2.universidad  =  universidad
panel.pareja.persona2.carrera  =  Carrera

panel.soltero.titulo = Soltero registrados esta noche
panel.soltero.columna.nombre  =  Nombre
panel.soltero.columna.apellido  =  Apellido
panel.soltero.columna.genero  =  Genero
panel.soltero.columna.edad  =  Edad
panel.soltero.columna.universidad  =  universidad
panel.soltero.boton.verDetalles  =  Ver detalles
panel.soltero.boton.emparejar  =  Emparejar
panel.soltero.nombre  =  Nombre
panel.soltero.apellido  =  Apellido 
panel.soltero.edad  =  Edad
panel.soltero.genero  =  Genero
panel.soltero.universidad  =  universidad
panel.soltero.carrera  =  Carrera

appsoltero.joptionpane.messagedialog.imagencargada.exitosa   =   Imagen cargada con éxito
appsoltero.joptionpane.messagedialog.controledad   =   Eres menor de edad aún. No es posible tu ingreso al bar
appsoltero.joptionpane.messagedialog.registroexitoso   =   Soltero registrado con éxito
appsoltero.joptionpane.excepciones.fechanacimiento   =   La fecha de nacimiento no es correcta
appsoltero.joptionpane.excepciones.genero   =   No ha seleccionado su género
appsoltero.joptionpane.excepciones.documento   =   Número de documento no válido
appsoltero.joptionpane.excepciones.apellido   =   Apellido no válido
appsoltero.joptionpane.excepciones.nombre   =   Nombre no válido
appsoltero.joptionpane.excepciones.universidad   =   Nombre de universidad no válido
appsoltero.joptionpane.excepciones.carrera   =   Carrera universitaria no válida
appsoltero.joptionpane.excepciones.imagen   =   No ha seleccionado una foto de perfil
appsoltero.joptionpane.excepciones.number   =   Número de documento no válido
appsoltero.joptionpane.documentonoregistrado   =   No se encuentra registrado ese documento

appsoltero.joptionpane.messagedialog.iniciosesioncorrecto.uno   =   Bienvenido, 
appsoltero.joptionpane.messagedialog.iniciosesioncorrecto.dos   =    a rutila
appsoltero.joptionpane.messagedialog.emparejar.nocorrecto   =   Selecciona un soltero para realizar esta acción
appsoltero.joptionpane.messagedialog.emparejar.noseencuentrasoltero   =   No se encontró el soltero
appsoltero.joptionpane.messagedialog.emparejar.seleccionincorrecta   =   No puedes emparejarte contigo mismo
appsoltero.joptionpane.messagedialog.emparejar.seleccioncorrecta   =   ¡Pareja formada con éxito!